name: Weekly report
on:
  schedule:
    - cron: 30 15 * * SAT
  workflow_dispatch:
permissions:
  issues: write

jobs:
  report:
    name: Create Weekly report
    runs-on: ubuntu-latest
    steps:
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: work
      - name: Checkout vim
        uses: actions/checkout@v2
        with:
          repository: vim/vim
          path: vim
      - name: Build report
        run: |
          bash work/tools/script/get_doc_info.sh
          echo Update ${{ steps.current-time.outputs.ISOTime }} >> doc_info.md
      - name: Create issue
        uses: peter-evans/create-issue-from-file@v3
        with:
          title: Weekly help diff
          content-filepath: ./doc_info.md
          issue-number: 968
            # issue-number: if removed, create new issue/if define issue num, update numbered issue.
